conversation/ui

src/TextField/TextField.jsx, src/TextField/stories.jsx
This PR allows the `TextField` component to pass the `fullWidth` property to its underlying `FormControl` component, allowing any text field to have a full width if desired.
This PR also proposes a left aligned grid container for `TextField` stories, as a centralized view in combination with the new full width example made the field group above the full width to never be aligned.
=> Allow the `TextField` component to receive the full width property

README.md, package-lock.json, package.json, src/styles/ThemeProvider.jsx
Adds some optional props to `ThemeProvider` to support server side rendering.
Based on:
https://material-ui.com/guides/server-rendering/
https://github.com/cssinjs/jss/blob/master/docs/ssr.md
=> Allow registering JSS for server side rendering

CHANGELOG.md, package.json, src/ComponentOverview.jsx, src/TextField/TextField.jsx, src/TextField/stories/index.jsx, src/TextField/stories/overview.jsx, src/TextField/stories/states.jsx, src/TextField/stories/types.jsx, src/util.jsx
This PR adds documentation for the `<TextField>` component.
* Run `make storybook`
* Open `localhost:9001` and check it out
=> Add text field component documentation

.storybook/addons.js, .storybook/config.js, package-lock.json, package.json, src/index.js, src/styles/ThemeProvider.jsx
This PR adds the ability for the storybook theme to be changed at runtime. This will be useful when we want to see the effect that different themes have on our components.
Depends on #10.
=> TC-435 Allow the storybook theme to be changed dynamically

package-lock.json, package.json, rollup.config.js
Replaces our manually curated list, which was [causing hard to diagnose problems](https://github.com/conversation/tc/pull/8753) with a plugin that uses our `package.json` to automatically populate the list of external dependencies:
https://www.npmjs.com/package/rollup-plugin-auto-external
=> Automatic external dependency configuration for rollup

src/styles/themes/legacy.js
I've notice this before, but confirmed today with @ZoeJazz that the `body2` variant typography seemed "not quite fit" for its use cases. I confirmed with her that "Noto Sans" should be the font to be used on any type of "labeled information", while "Libre Baskerville" will be used for content reading due to being a serif font.
----
----
----
----
=> [RFC] Use Noto Sans font-family for body2

CHANGELOG.md, src/Dropdown/Dropdown.jsx, src/Dropdown/Dropdown.test.jsx, src/Dropdown/stories/events.jsx, src/Dropdown/stories/index.jsx, src/TextField/TextField.jsx, src/TextField/TextField.test.jsx, src/TextField/stories/events.jsx, src/TextField/stories/index.jsx
For TC Donations, we use `onBlur` events to do some Google tracking. For example, as a donor progresses through the form, we track a number of events as to which fields they completed, or left blank, etc...
However, we only explicitly passed along `onChange`. I've added `onBlur` and `onFocus` to the `TextField` and `Dropdown` components, plus added specs and demonstrations in the storybook.
=> [TC-688] Add events to TextField and Dropdown

package-lock.json, package.json, src/ChipInput/ChipInput.jsx
This PR adds the `id` prop to `propTypes` and applies it to the input.
In addition, it adds a `prepare` section to the npm scripts, to allow for using the component library directly from GitHub without publishing to the registry.
=> TC-48 ChipInput tweaks

src/form/FormLabel.jsx, src/styles/themes/legacy.js
This PR sets the default font to Noto Sans for the `legacy` theme, and the label font size/weight is gently changed.
=> [TC-703] Update input field UI

CHANGELOG.md, src/Autocomplete/Autocomplete.jsx, src/Autocomplete/Autocomplete.test.jsx, src/Autocomplete/stories/events.jsx, src/Autocomplete/stories/index.jsx
Seems Downshift generates an id (like `downshift-[INTEGER]-input`), and hijacks the events, to make it work the way it wants (to display an autocomplete).
I've explicitly set the id and onBlur so it uses a given prop, or the generated downshift ones.
@nullobject and @tiagoamaro, I'd love your expertise on this.
=> Add id, onBlur, and onFocus props to Autocomplete component

CHANGELOG.md, src/Autocomplete/Autocomplete.jsx, src/Autocomplete/Autocomplete.test.jsx
This PR allows the Autocomplete to pass the input field's `name` prop to the underlying TextField.
TC Donations uses the name prop (ala `donation["country"]`) to validate the fields, and send the response to the server. Without it, the `country` attr on the `Subscription` is `nil`.
=> Allow Autocomplete to pass the name prop to the underlying Textfield

src/Autocomplete/Autocomplete.jsx
This PR replaces the reference of the `withStyles` high order component (HoC) at the `Automcomplete` component from the `@theconversation/ui` reference to its packaged `@material-ui/core/styles` implementation.
With a little help of `git-bisect`, I've found that PR's https://github.com/conversation/ui/pull/33 single commit, where the `Autocomplete` component was introduced, was the culprit of making the `make doc` command of being broken. The only difference between how the `Autocomplete` component was written between others was on how Material UI's `withStyles` high order component (HoC) was imported.
Other `@theconversation/ui` components import straight from `@material-ui/core/styles`, while the `Autocomplete` was importing it from the own library `index.js`.
This is not a problem on …
=> Use MUI `withStyles` instead of `@theconversation/ui/withStyles`

CHANGELOG.md, src/Autocomplete/Autocomplete.jsx, src/TextField/TextField.jsx, src/TextField/TextField.test.jsx
You can now specify the `autoComplete` prop as either a boolean or string value for the `TextField` component.
This little bit of sugar should it a touch nicer to use. For example, you don't need to use `autoComplete='on'` to enable autocomplete anymore:
<TextField autoComplete />
or if you want anything else:
<TextField autoComplete='email' />
=> [TC-822] Allow specifying the autoComplete prop as a boolean or string

CHANGELOG.md, src/TextField/TextField.jsx, src/TextField/stories/states.jsx
I noticed an issue where a custom background colour for the `<input>` element was being clipped. For example, Safari sets a light yellow background colour if you auto-fill the fields.
Notice how the rounded corners are being clipped:
To fix this we need to hide overflow on the wrapping container.
=> [TC-832] Fix TextField overflow

CHANGELOG.md, src/dialog/DonationDialog.jsx, src/dialog/stories/donationDialog.jsx
This PR fixes an issue with the ARIA label for the close button on the `DonationDialog` component.
=> Set aria-label on DonationDialog close button

CHANGELOG.md, src/dialog/DonationDialog.jsx
This PR makes an adjustment to the `DonationDialog` actions bottom margin.
By using a 4x multiple of the `theme.spacing.unit` variable (which is 8px by default), we end up with 32px. This means that we can scale this margin with the rest of the spacing, if we change the theme spacing later.
=> [TC-855] Set the DonationDialog actions bottom margin to 32px

src/Avatar/Avatar.jsx, src/Button/Button.jsx, src/Button/Button.test.jsx, src/ComponentOverview.jsx, src/dialog/DonationDialog.jsx, src/dialog/stories/donationDialog.jsx, src/index.js, src/promo/ArticleDonationBanner.jsx, src/promo/ArticleDonationBanner.test.jsx, src/promo/stories/article_donation_banner.jsx, src/promo/stories/index.js, src/styles/themes/default.js
This adds the article donation banner component. The component itself is really pretty simple, so the value is mostly in the examples. The child node splitting is the only real complicated part, this is mostly due to some unanswered questions to do with our themes and colour palettes that we should revisit.
This is what it looks like:
I haven't added the "small layout" detection stuff yet. Mostly so we can get this into TC now. Will start working on that now (for merging in another PR).
=> Add article donation banner

src/styles/ThemeProvider.jsx
In TC we render multiple react trees, because the React must live alongside legacy code.
This means that in TC we need to be able to share the class name generator across each instance of a ThemeProvider. If the generator is not shared, it's highly likely that the generated classnames will
clash and cause components to have the incorrect styles applied to them.
Adding this prop allows us to share the same instance of name generator and avoid this problem.
ref: https://material-ui.com/customization/css-in-js/#creategenerateclassname-options-class-name-generator
The MUI docs seem to imply that it's the SheetsManager that needs to be shared, but that didn't work. 
I found it was only necessary to share the name generator to get the desired behaviour.
What led me down that path was some …
=> Allow sharing of class name generator across each ThemeProvider

src/Person/Person.jsx, src/dialog/DialogContent.jsx
Increased spacing between avatar and person caption
~~Decreased spacing below button to match what's in the design (had to fix some side effects of the avatar change and this was in the area)~~ Removed from PR.
=> TC-895 Tweak promo spacing

src/dialog/DonationDialog.jsx, src/promo/DonationBanner.jsx, src/promo/ThinDonationBanner.jsx
TC has a lot of baggage we can't get rid of just yet. This marks more link text colours as `!important` so that TC's ambitious link styles don't mess with the component library.
See also:
https://github.com/conversation/ui/pull/51
Examples of the problem:
=> Fix more global CSS colour conflicts

CHANGELOG.md, src/Dropdown/Dropdown.jsx
We were seeing a faint background colour to the right of the `Dropdown` when `:focus`; the `padding-right` was a smidge too big.
=> [TC-900] Fix overflow when focused on DropDown components

CHANGELOG.md, src/promo/DonationBanner.jsx, src/promo/DonationBanner.test.jsx, src/promo/DonationDialog.test.jsx, src/promo/stories/donationBanner.jsx, src/promo/stories/donationDialog.jsx
This PR adds an `open` prop to the `DonationBanner` component. This allows it to behave in much the same way as the `DonationDialog` component, where it is not visible when `open` is set to `false`.
I also refactored the `DonationDialog` story to use the react hooks API.
- Fire up storybook: `make storybook`
- Check that you can close the donation banner
=> [TC-942] Add open prop to the DonationBanner component

CHANGELOG.md, src/promo/ArticleDonationBanner.jsx
@ZoeJazz noticed that the background colour for the `ArticleDonationBanner` should be `#f8f8f8`.
I hard-coded this value, but perhaps we should look at adding it to our gray palette?
=> [TC-947] Tweak the ArticleDonationBanner background colour

src/TextField/TextField.jsx, src/TextField/stories/types.jsx
If the field isn't email you don't get the nice keyboard behaviour on mobile devices (automatic lowercase, and shortcut to @ symbol).
Needed for donations app.
=> Allow text field type 'email'

CHANGELOG.md, src/promo/DonationDialog.jsx
This PR updates the breakpoints for the `DonationDialog` component.
With these new breakpoints, we have:
- For small devices, a 24px horizontal margin around the dialog. It is anchored to the top of the screen and will grow vertically to fit the the dialog content.
- For medium-large devices, the dialog is vertically and horizontally centred on the page.
If anyone knows an easier way to do this, I am all ears 👂
- Fire up storybook and check out the `DonationDialog` at various sizes.
Small:
Large:
Small:
Large:
=> Amend pop up margin on mobile to match original design

src/Button/stories/colours.jsx, src/Button/stories/variants.jsx
REFS https://trello.com/c/qi1Gl3ai/506-tcui-show-buttons-with-theme-colours
Since https://github.com/conversation/ui/pull/75 merged, we now have access to themes! I thought a good candidate for showing off the theme options is to show the `Button` component in each theme.
And the variants:
=> [506] Add storybook examples of Buttons wrapped in each colour theme

src/Autocomplete/Autocomplete.jsx, src/promo/ArticleDonationBanner.jsx, src/util.jsx
Upgrading MaterialUi v4 was more difficult than it needed to be because every test failed due to requiring from `./index.js`.
One problem in the index would propagate to every other spec, e.g.
A date picker had a legit failure, but we were seeing it fail in autocomplete, buttons, etc...
=> Change components to not require via root-level index

package-lock.json, package.json, src/Autocomplete/Autocomplete.jsx, src/Autocomplete/Autocomplete.test.jsx, src/ChipInput/ChipInput.jsx, src/ChipInput/ChipInput.test.jsx, src/ComponentOverview.jsx, src/Typography/stories/variants.jsx, src/divider/MiniDivider.jsx, src/form/FormLabel.jsx, src/pickers/DatePicker/DatePicker.jsx, src/pickers/DatePicker/DatePicker.test.jsx, src/pickers/DateTimePicker/DateTimePicker.jsx, src/pickers/DateTimePicker/DateTimePicker.test.jsx, src/pickers/TimePicker/TimePicker.jsx, src/pickers/TimePicker/TimePicker.test.jsx, src/promo/ArticleDonationBanner.jsx, src/promo/ArticleDonationBanner.test.jsx, src/promo/DonationBanner.jsx, src/promo/DonationDialog.jsx, src/promo/ThinBanner.jsx, src/promo/ThinDonationBanner.jsx, src/styles/ThemeProvider.jsx, src/styles/themes/common.js, src/util.jsx
https://trello.com/c/OCkepBuq/526-update-materialui-to-420
To unblock https://github.com/conversation/ui/pull/78, @nickbrowne and I went about upgrading TCUI to use `@material-ui/core` to 4.2.0.
We also found that we had to upgrade `@material-ui/icons` and `@material-ui/lab` (due to peer dependencies), and `material-ui-pickers` was merged into MterialUI to become`@material-ui/pickers`.
=> [526] Update @material-ui to 4.2.0

CHANGELOG.md, src/dialog/DialogInlineTitle.jsx, src/promo/ArticleDonationBanner.jsx, src/promo/DonationBanner.jsx, src/promo/DonationBanner.test.jsx, src/promo/DonationDialog.jsx, src/promo/ThinDonationBanner.jsx
When we added the new themes, we naffed the donation-related banners' styling a smidge. This was because we changed the default colours and how we structured the themes.
I've made them look as expected again. Most of these are pulling in the `core` palette, and specifying the colour manually. The ones where we were setting backgrorund colours required this method.
One I could get away with using a `ThemeProvider` was in the below-article banner, as only the button needed colouring.
I think this is okay for now; we built those components pre-themes, so keeping them the same for now while we can generalise them for future use (like in the case of making the `ThinBanner`, which was a generalisation of the `ThinDonationBanner`).
=> [517] Fix existing TCUI donation related banners

CHANGELOG.md, src/index.js
REFS https://trello.com/c/9mlHdoKu/559-add-box-our-themes-and-palettes-to-tcui
I noticed that we could export a few more things, especially the themes and palettes; the themes we will need to wrap around other TCUI components to adjust their styling, and the palettes for when we need to use standardised colours..
=> [559] Add Box, themes and palettes to exports from TCUI

src/MessageTile/MessageTileButton.jsx
https://trello.com/c/M4GqZoGl/772-give-the-tcui-messagetile-more-spacing-at-the-bottom-below-the-button
```
Like framing a picture, we want a little extra space at the bottom so it looks lighter overall.
-Zoe.
```
Mock:
Screenshot:
=> Give the TCUI MessageTile more spacing at the bottom below the button

package-lock.json, package.json
https://trello.com/c/SZC5hsy6/783-lock-tcui-to-material-ui-core-420
This PR locks `@material-ui/core` to 4.2.0 and downshift to 3.2.7, and sets specific versions to material-ui related packages.
@nickbrowne and I looked at a js package upgrade on TC. on TC, Most of the changes came from TCUI. This PR locks those versions down (removes the `^`).
Then, upgrades should be by a choice, and then pushed to TC.
When we bump material-ui/core to 4.3.2 in a future PR, downshift needs to upgrade to v4.0.0 then.
=> Lock material-ui/core to 4.2.0

CHANGELOG.md, package-lock.json, package.json
https://trello.com/c/Q43rDx7e/784-bump-tcui-material-ui-core-to-432
Relies on https://github.com/conversation/ui/pull/88 being merged
@material-ui wants to be upgraded lcokstep with it's other packages.
- @material-ui/core: 4.3.2
- @material-ui/icons: 4.2.1
- @material-ui/lab: 4.0.0-alpha.23
- @material-ui/pickers: 3.2.2
- deepmerge: 4.0.0
and because it upgrades required babel/runtime version:
- @babel/runtime: 7.5.5
=> Bump @material-ui/core to 4.3.2

CHANGELOG.md, src/MessageTile/MessageTileButton.jsx, src/MessageTile/stories/examples.jsx, src/MessageTile/stories/index.jsx, src/MessageTile/stories/messageTile.jsx
https://trello.com/c/QhX47tvY/991-show-more-examples-of-messagetile-components
A point raised in a team meeting was that we should show better examples of how our newer configurable components can be used.
We're aiming to deprecate the older, hardcoded promos:
- `ArticleDonationBanner`
- `DonationBanner`
- `DonationDialog`
- `ThinDonationBanner`
In favour of using newer, configurable components:
- `ThinBanner`
- `ThickBanner`
- `MessageTile`
This PR will tidy up the examples of MessageTile, and **enhance it to fully-replicate** the `EndOfArticle` component (which used `ArticleDonationBanner` under the hood, but now can be done with `MessageTile`). 
The enhancements add two props to `MessageTileButton` to enable it to meet all the requirements we currently have for it.
=> Show more examples of MessageTile components + enhance MessageTile

src/StickyPopup/StickyPopup.jsx, src/StickyPopup/StickyPopup.test.jsx, src/StickyPopup/StickyPopupDismiss.jsx, src/StickyPopup/index.js, src/StickyPopup/stories/Examples.jsx, src/StickyPopup/stories/StickyPopup.jsx, src/StickyPopup/stories/index.jsx, src/ThickBanner/ThickBanner.jsx, src/util.jsx
REFS https://trello.com/c/zQvueItJ/1000-sticky-popup
REFS https://trello.com/c/yjOzW8cl/1008-build-sticky-popup-component-in-tcui
- MUI: https://material-ui.com/components/snackbars/ + https://material.io/components/snackbars/
- Our design: https://gallery.io/projects/MCHbtQVoQ2HCZWiQBR82z4LY/files/MCEJu8Y2hyDScXXP1OFK2xzMOO7rIvg1d1Y
This update is one of many design recommendations for enhancing our email experience. The intention is that a snackbar would appear after 60-80% scroll on an article page. It could promote newsletter subscription today (purple), be reused for donations later in the year (red) and potentially be a consideration for republishing promos (default blue grey). Like all components, the snackbar should be device agnostic. 
This PR creates a `StickyPopup` component. …
=> Build StickyPopup components 

CHANGELOG.md, src/Typography/Typography.jsx, src/styles/themes/common.js
https://trello.com/c/k7EZNukl/935-add-support-for-responsive-typography-variants-to-component-library
https://trello.com/c/uEHMo2ee/1061-set-new-tcui-default-font-sizes
This is part 1 of breaking up https://github.com/conversation/ui/pull/102
This alleviates the themes of knowing too much about the typography, and instead imbues the `Typography` component with knowing how to size itself.
Originally, in https://github.com/conversation/ui/pull/102, I'd added the styles to the common theme; this caused third party components to display a bit out of whack.
Now, if we only set the base font to Noto Sans and the size to 16px, it keeps th e third party components looking as expected (with minor visual differences), and any component using our own Typography component will require _minor_ updates …
=> Updates font sizes for Typography component

src/ArticleDonationBanner/stories/ArticleDonationBanner.jsx, src/DonationBanner/DonationBanner.jsx, src/DonationDialog/stories/DonationDialog.jsx, src/MessageTile/MessageTileBody.jsx, src/MessageTile/MessageTileHeader.jsx, src/ThickBanner/ThickBanner.jsx, src/dialog/DialogInlineTitle.jsx, src/dialog/DialogTitle.jsx, src/dialog/stories/content.jsx, src/pickers/stories/usage.jsx
https://trello.com/c/k7EZNukl/935-add-support-for-responsive-typography-variants-to-component-library
https://trello.com/c/uEHMo2ee/1061-set-new-tcui-default-font-sizes
This is part 2 of breaking up https://github.com/conversation/ui/pull/102
It relies on https://github.com/conversation/ui/pull/103
This updates the components to use as close a typographic variant as possible. Very few of these components are documented in [Gallery](https://gallery.io/projects/MCHbtQVoQ2HCZWiQBR82z4LY), so it's picking from the [Typography variants](http://styleguide.theconversation.com/?path=/story/typography--variants) that appear visually similar.
Left is this PR, right is master
**Now**, a bunch of components needed tweaks. Most were changing a `h5` to ` h3` or so. Some will require changes on TC's …
=> Update TCUI components to use new font sizes

CHANGELOG.md, src/Typography/Typography.jsx, src/styles/themes/common.js
https://trello.com/c/k7EZNukl/935-add-support-for-responsive-typography-variants-to-component-library
https://trello.com/c/Cteo0DGU/1063-apply-device-width-responsive-typography-variants-to-component-library
This is part 3 of breaking up #102
It relies on #103 and #104 
This updates the `Typography` component to add desktop- breakpoint font sizes.
- h1 - 28px (44px on desktop)
- h2 - 26px (32px on desktop)
- h3 - 22px
- h4 - 20px
- h5 - 18px
- h6 - 16px
- Overline - 14px (16px on desktop)
- Subtitle 1 - 16px
- Subtitle 2 - 12px
- Caption - 12px
- Button - 14px (16px on desktop)
- Body 1 - 16px (18px on desktop)
- Body 2 - 18px (24px on desktop)
=> Apply device-width responsive Typography variants to component library

src/StickyPopup/StickyPopup.jsx, src/StickyPopup/StickyPopup.test.jsx, src/StickyPopup/stories/ClickAwayClose.jsx, src/StickyPopup/stories/index.jsx
https://trello.com/c/lSKswxhI/1081-add-optional-non-default-click-away-closes-the-popup-functionality
The StickyPopup (more specifically, the underlying Snackbar) by-default had behaviour that clicking away closed the popup.
This is because it wasn't _meant_ to have a dismissable "X". 
No problem!
So, now, by default the click away handlers do nothing.
We can also optionally set them to when clicked away, it closes the StickyPopup.
To view, http://localhost:9001/?path=/story/stickypopup--click-away-close
=> Add optional non-default click-away closes the popup functionality

src/StickyPopup/StickyPopup.jsx, src/StickyPopup/stories/Examples.jsx, src/Typography/Typography.jsx, src/styles/themes/common.js
After trying out the `StickyPopup` in TC for real, we found a few minor issues that are worth fixing before we ship it.
- Removed letter spacing from `button` typography variant
- Ensured button text is bold as intended
- Set line height of `subtitle1` to 1.3 so it's not as spaced out
- Increased the padding to prevent text from slamming against the "x" button
- Updated examples to closer match mockups
Before:
After:
=> Sticky popup related fixes

src/DonationDialog/DonationDialog.jsx
Looks like docs went stale
The example uses `substitle1` not body, so we should reflect that in the docs.
- Note: I haven't updated the CHANGELOG in this because the current changelog accurately reflects the current state.
=> Update UI Docs to reflect example

CHANGELOG.md, src/MessageTile/MessageTileHeader.jsx
https://trello.com/c/R6Tj8iLT/1329-change-messagetileheader-from-h3-to-h5-to-bring-it-into-line-with-designs
To bring the MessageTile inline with @ZoeJazz's designs, we need to bump the
heading down a smidge to h5.
Raised inhttps://github.com/conversation/tc/pull/9348#issuecomment-549190088
Left is master, right is this PR:
And the docs to match them against: https://gallery.io/projects/MCHbtQVoQ2HCZWiQBR82z4LY/files/MCEJu8Y2hyDScTrgA6mNBmQtHZ7tLvHQhN0
=> Change MessageTileHeader from h3 to h5 to bring it into line with designs

CHANGELOG.md, src/Typography/Typography.jsx
This isn't ideal, but it was far harder than expected to quarantine TC's styles. (biggest blocker and bordering on impossible to change at the moment is the content pipeline). This ended up being the easiest way to prevent TC's legacy CSS from messing with MUI typography heading variants.
Initially I planned to reset every property that we set in TC (like the trello card mentions), but that caused additional problems due to class specificity and the way MUI mixes classes together to build the styles for Typography components.
In the end, I experimented until I only had resets for just the properties that were likely to cause (and have caused) the most grief while effectively being a no-op visually - so if you are testing locally, you shouldn't see any visual differences in this PR.
This …
=> Add resets to heading typography variants

src/Typography/Typography.jsx
https://trello.com/c/ZMtljzYf/1361-update-storybook-with-selected-font-sizes
**Why**
Based on better responsive design and accessibility, we've adjusted font sizes / line heights to: 
h1: 38px for desktop only
Body 1: 1.6 line height across desktop and mobile 
We've [made the changes on TC](https://github.com/conversation/tc/pull/9342), and need to back up those changes in TCUI
=> Update storybook with selected font sizes

src/MessageTile/stories/examples.jsx
https://trello.com/c/CfgJGmwb/1421-show-use-of-sizesmall-button-on-republishpanel-examples
**Why**
The MessageTile was designed for text of the length "Republish for free", but implemented on TC with "Republish this article".
This caused some line wrapping, so we decided to use the `small` variant of the `Button`.
This _only_ changes the example in Storybook. The changes are already implemented on TC.
**Before**
**After**
=> Change example of MessageTile to have match how it's implemented on TC

Makefile, babel.config.js, package.json
Right now when using any single component from this library, you get everything but the kitchen sink whether you like it or not, which isn't ideal.
With a couple of tweaks we can let webpack at least discard parts that don't actually get used with [tree shaking](https://webpack.js.org/guides/tree-shaking/).
In the following screenshots you can see (we've got a lot of work to do... but anyway) that when part of the ui library doesn't get used, it drops out of the bundle automatically. In this example, it's what happens when you don't use the datepicker.
=> Add tree shaking support

CHANGELOG.md, src/DonationDialog/DonationDialog.jsx
**Why?**
We want to edit our donation dialog target container, instead of always appending it to `document.body` [1]
[1] https://material-ui.com/api/modal/#props
=> Allow donation dialog to pass props to Material UI's dialog

CHANGELOG.md, src/TextField/TextField.jsx, src/TextField/TextField.test.jsx, src/TextField/stories/states.jsx
**Why?**
We want to have a visual feedback of the character limit of a text field
**How?**
State management happens inside the `TextField` component, being flexible enough to work when:
- Passing the `defaultValue` or `value` prop (counting initial values)
- Input with a `helperText` prop
- `multiline` inputs
**Manual testing steps**
- Checkout this branch
- Run the storybook (e.g.: `make storybook`)
- Visit the `TextField` states story (e.g.: http://localhost:9001/?path=/story/text-fields--states)
- You should see the new "Maximum length validation" input in the "Example" field
**Screencast**
=> Max characters client side validation

CHANGELOG.md, src/Dropdown/Dropdown.jsx
The `Dropdown` value prop can receive a "number" in situations where we're handling IDs.
=> Dropdown component value prop should accept number or string types

CHANGELOG.md, package-lock.json, package.json
I'd like to use the <Backdrop /> component to display a modal loading indicator in donations, but the component in 4.3.2 has a bug where the [children aren't displayed](https://github.com/mui-org/material-ui/pull/17115). This bug is fixed in 4.4.3.
Full list of changes in material-ui:
https://github.com/mui-org/material-ui/compare/v4.3.2...v4.4.3
=> Upgrade material-ui to 4.4.3

CHANGELOG.md, src/TextField/TextField.jsx, src/TextField/TextField.test.jsx
After [upgrading material-ui](https://github.com/conversation/ui/pull/138), but before this PR, we were receiving this error (and also an analogous one for formHelperText):
> Material-UI: The key `formLabel` provided to the classes prop is not implemented in ForwardRef(InputBase).
> You can only override one of the following: root,formControl,focused,disabled,adornedStart,adornedEnd,error,marginDense,multiline,fullWidth,input,inputMarginDense,inputSelect,inputMultiline,inputTypeSearch,inputAdornedStart,inputAdornedEnd,inputHiddenLabel.
=> Avoid passing non-MUI classes to MUI

CHANGELOG.md, src/Dropdown/Dropdown.jsx, src/Dropdown/Dropdown.test.jsx, src/Dropdown/stories/events.jsx, src/Dropdown/stories/index.jsx, src/Dropdown/stories/states.jsx, src/Dropdown/stories/variants.jsx
**Why?**
MUI custom select creates too much friction for users and test utilities. Let's use the native version instead.
If we want to use it anyway, we can disable the native version by passing the `<Dropdown native={false} />` prop.
**How to test  it?**
- Checkout this branch
- Run storybook (e.g.: `make storybook`)
- Read the new documentation on "Dropdown" overview (e.g.: http://localhost:9001/?path=/story/dropdowns--overview)
- See the native select in action checking the "Dropdown" "States" stories (e.g.: http://localhost:9001/?path=/story/dropdowns--states)
=> use native select for Dropdown component

CHANGELOG.md, src/TextField/TextField.jsx, src/TextField/stories/states.jsx
The root cause of https://trello.com/c/S2U0mYF9/5338-fix-error-text-colour-regression is the fact that https://github.com/conversation/ui/pull/136 made a separation between a `TextField`'s `error` prop, and the `errorState` state variable. TC-Donate is trying to make its inputs look like they have errors by setting the prop, but the state variable isn't changing, so the inputs keep their benign grey appearance.
This commit ensures the component always pays attention to the `error` prop whilst not breaking the char count functionality introduced in https://github.com/conversation/ui/pull/136 by considering both at the same time when determining whether to show the component in an error state. It makes `errorState` fully independent from the value of `error` and renames it to make it …
=> Disentangle error prop and error state in Text Field

package-lock.json, package.json
**Why?**
We want to be able to add icons to the start/end of buttons, which was made available on @material-ui/core version 4.5.0 [1].
Since we're on version 4.4.3 and version 4.5.0 was the exact following version of it, let's just bump this minor version.
[1] https://github.com/mui-org/material-ui/blob/next/CHANGELOG.md#450
**Testing steps**
According to [MUI's 4.5.0 changelog](https://github.com/mui-org/material-ui/blob/next/CHANGELOG.md#450), there were only improvements and small fixes without any breaking changes, most of those on buttons.
Our storybook buttons should be working as usual, so it would be good installing this branch's dependencies and comparing to `master` buttons to see if there's any difference.
=> Bump @material-ui/core minor version (4.4.3 -> 4.5.0)

package-lock.json, package.json, src/styles/ThemeProvider.jsx
**Why?**
MUI introduced their [`Autocomplete` component](https://material-ui.com/components/autocomplete/) on version 4.5.2 and labs 4.0.0-alpha30.
We'll want to use that in the future, so let's update both packages.
=> Bump versions: material UI core (4.5.0 -> 4.5.2) and labs (4.0.0-alpha23 -> 4.0.0-alpha30)

.travis.yml, package-lock.json
This should let us set up export mappings to optimise the imports for apps which use this library (not done yet).
Have tested build on Node 14 against TC and it appears to work fine.
=> Switch build to use Node LTS 14

src/Dropdown/Dropdown.jsx, src/TextField/TextField.jsx
**Why?**
We want to be able to render React components on `TextField`s and `Dropdown`s labels without prop type validation errors.
Since both components render their labels using MUI `FormLabel` component, we can safely change its prop type to `node`, so it matches MUI `FormLabel` children prop type.
Documentation: https://v4-5-2.material-ui.com/api/form-label/#formlabel-api.
=> Allow text fields and dropdowns labels to be React components

package-lock.json, package.json
In TC there's a problem where we are ending up with slightly different versions of mui core and styles, which means that the
styles code is accessing properties in core which don't exist.
Easiest way to solve this is locking down the version number of styles so that it matches core, rather than just letting npm install random minor versions that are incompatible.
A bit hard to test because it involves code that hasn't/can't merge yet on TC but here's a before and after:
```
FAIL  app/assets/javascripts/lib/renderReactWithStyles.spec.js
● Test suite failed to run
TypeError: Cannot set property 'displayName' of undefined
4 | import hypernova from "hypernova";
5 | 
> 6 | import { ServerStyleSheets } from "@material-ui/styles";
| ^
7 | 
8 | // A custom renderer which extracts JSS required by …
```
=> Ensure mui styles and core libs are the same version

CHANGELOG.md, package-lock.json, package.json, src/styles/themes/accent.js, src/styles/themes/common.js, src/styles/themes/core.js, src/styles/themes/default.js
**Why?**
We're aiming to use tooltips on components that will show quick pieces of information of a certain entity while navigating through a page designed with this system.
On a page that mixes up absolute positioned components, such as dialog backdrops and tooltips, we want to ensure that modals are going to appear on top of tooltips.
**Screenshots**
- Before
- After
=> Swap z-index values between tooltips and modals

package.json
**Why?**
We don't want to force projects using this UI lib to have `lodash` version 4.17.21. Let's increase the version range to the patch version, using the caret syntax.
=> Relax lodash dependency version

package-lock.json, package.json, src/styles/ThemeProvider.jsx
They both perform the same function, but using MUI's built in StylesProvider should result in a smaller bundle for TC once we upgrade to npm 7.
Depends on https://github.com/conversation/tc/pull/11337
=> Use MUI StylesProvider instead of react-jss JssProvider

Dockerfile, Makefile, README.md, docker-compose.yml
@ZoeJazz would like to run storybook to be able to make changes to our UI components. However, there's currently no Docker config, which makes it quite complex to run for anyone without a machine-level node install. This PR adds a `make storybook-docker` task that spins up storybook inside docker.
=> Add config to run storybook through Docker

src/Button/Button.jsx
Align with brand guidelines for shadows - we'd like subtle shadows only.
=> Override MUI box shadow to lighten it

README.md
We are no longer using Travis. Let's show our GitHub actions status on the README.
=> Replace Travis badge with GitHub actions

.github/workflows/package.yml
There were a couple of issues with the new GitHub package workflow:
* We were publishing an empty package, this is because we forgot to build it first.
* We weren't uploading the storybook docs to S3
Both of these things have been addressed, and test packages have been built and deployed.
This also required creating a couple more organisation-level secrets for our AWS credentials (they are also in 1Password).
=> Make sure that the package is built before it is published

Dockerfile
We want all our docker images to use the same ubuntu base, so we should use that image here instead of the alpine one.
See:
* https://github.com/conversation/docs/blob/main/adr/20211006-use-ubuntu-20-04-for-base-docker-images.md
* https://github.com/conversation/docker-images/pull/19
=> Use ubuntu node 16 image

.github/workflows/package.yml
We've deprecated this UI library and no longer want to make the storybook accessible, so this removes the actions to build and publish it.
=> Remove storybook publication

.github/workflows/test.yml, .gitignore, bin/package_lock_lint.sh, package-lock.json, package.json
The [revised](https://conversation.slack.com/archives/C024N6U4QP7/p1648792330600059) [design](https://www.figma.com/file/qUZyvb3qPKiOK2lOGGoXhw/Donations---Gift-Aid?node-id=0%3A1) for Donations' Gift Aid inputs involves a tooltip with an arrow. The arrow feature MUI's `Tooltip` component arrived in [version 4.7.0](https://github.com/mui/material-ui/blob/HEAD/CHANGELOG.old.md#470) and received its final bugfix for the major version we currently use (v4) in [version 4.10.1](https://github.com/mui/material-ui/blob/HEAD/CHANGELOG.old.md#4101).
n.b. version 4.12.0 [deprecates `createMuiTheme`](https://github.com/mui/material-ui/blob/HEAD/CHANGELOG.old.md#material-uicore4120), which is a [breaking change](https://github.com/conversation/ui/runs/5845381547?check_suite_focus=true#logs) for us, so …
=> Upgrade MUI core to 4.10.1

src/Dropdown/Dropdown.jsx, src/Dropdown/Dropdown.test.jsx, src/Dropdown/stories/states.jsx
With the upgrade to version 2.41.0 of this library, testing library in donations has effectively [started complaining](https://buildkite.com/conversation/tc-donations/builds/14481#7fcee22d-9468-4f7d-a293-f8e987799f72) that TC-UI `Select` elements do not have  ids (it can't find the associated form control for the label the spec is searching for, because the associated form control doesn't have the id we're passing in).
Given a `Dropdown` component with an id of `"xyz"`, the DOM should include a `select` with an id of `"xyz"` as well as a label with a `for` attribute of `"xyz"`.
- Checkout this branch
- Run `make storybook`
- Check the Dropdowns > States page (e.g. http://localhost:9001/?path=/story/dropdowns--states) and note that the `select` elements in the DOM have the ids specified in …
=> Pass id to Select in Dropdown

Dockerfile
This upgrade is mostly for consistency with other apps, which upgraded as part of addressing an issue installing node from nodesource while building development docker images.
See:
* https://github.com/conversation/docker-images/pull/31
* https://github.com/nodejs/node/blob/v16.15.0/doc/changelogs/CHANGELOG_V16.md
=> Use node 16.15.0

src/Typography/Typography.jsx, src/Typography/stories/variants.jsx
This PR allows preserving newline characters in the `Typeography` component. It only applies to the `body1` and `body2` variants.
=> Allow whitespace in typeography component

Dockerfile
See:
* https://github.com/conversation/docker-images/pull/42
* https://nodejs.org/en/blog/vulnerability/june-2023-security-releases
* https://nodejs.org/en/blog/release/v16.20.1
=> Upgrade to Node 16.20.1
